version: '3.8'

services:
  data-gateway:
    build:
      context: ../../services/data-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - gateway-data:/app/data
    networks:
      - reef-network
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=robotics
      - MONGODB_COLLECTION=locations
    restart: unless-stopped
    depends_on:
      - mongodb

  map-dashboard:
    build:
      context: ../../web/map-dashboard
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../../web/map-dashboard:/app
    networks:
      - reef-network
    environment:
      - API_URL=http://data-gateway:8080
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    depends_on:
      - data-gateway
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reef-network

networks:
  reef-network:
    driver: bridge

volumes:
  gateway-data:
  mongodb_data: 